name: Block Direct Pushes

on:
  push:
    branches:
      - develop

jobs:
  block-direct-push:
    runs-on: ubuntu-latest

    steps:
      - name: Prevent direct push to develop
        run: |
          echo "Direct pushes to the develop branch are not allowed."
          exit 1
